---
- name: Copy all files from /tmp to /home/ubcustom/deployments/kamote as root and set ownership
  hosts: all
  become: yes
  remote_user: root
  vars:
    destination_dir: "/home/ubcustom/deployments/kamote/"
  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ destination_dir }}"
        state: directory
        owner: oracle
        group: dba
        mode: '0755'

    - name: Copy all files from /tmp to the destination directory
      copy:
        src: "/test"
        dest: "{{ destination_dir }}"
        remote_src: yes

