---
- name: Copy files from 192.168.100.32:/tmp/dep/ to /home/ubcustom/deployments/kamote/ as root
  hosts: all
  gather_facts: false
  vars:
    src_host: 192.168.100.32
    src_path: /tmp/dep/
    dest_path: /home/ubcustom/deployments/kamote/
  tasks:
    - name: Synchronize files from remote src_host to this managed node as root
      ansible.builtin.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        mode: pull
        archive: true
        compress: true
        times: true
      delegate_to: "{{ src_host }}"
      become: true
      become_user: root
