---
- name: Copy all files from 192.168.100.33:/tmp/dep/ to all hosts, preserving access
  hosts: all
  gather_facts: false
  vars:
    src_host: 192.168.100.33       # Ensure this is correct!
    src_path: "/tmp/dep/"            # Trailing slash!
    dest_path: "/tmp/dep/"           # Trailing slash!
  tasks:
    - name: Synchronize all files and folders from src_host to this managed node
      ansible.builtin.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        mode: pull
        archive: true
        compress: true
        times: true
      delegate_to: "{{ src_host }}"
      become: true
