---
- name: Copy files from 192.168.100.32:/tmp/dep/ to all hosts, preserving access
  hosts: all
  gather_facts: false
  vars:
    src_host: 192.168.100.32
    src_path: /tmp/dep/
    dest_path: /tmp/dep/
  tasks:
    - name: Synchronize files from remote src_host to this managed node
      ansible.builtin.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        mode: pull
        archive: true   # Preserves permissions, ownership, timestamps
        compress: true
        times: true
      delegate_to: "{{ src_host }}"
      become: true
