---
- name: Move all SQL files from /tmp to /home/ubcustom/deployments/kamote as root, then chown oracle:dba
  hosts: all
  become: yes
  remote_user: root
  vars:
    destination_dir: "/home/ubcustom/deployments/kamote"
  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ destination_dir }}"
        state: directory
        owner: oracle
        group: dba
        mode: '0755'

    - name: Move all SQL files from /tmp to the destination directory
      command: mv "{{ item }}" "{{ destination_dir }}/"
      with_fileglob:
        - "/tmp/*.sql"
      args:
        removes: "{{ item }}"

    - name: Change ownership of all SQL files in the destination
      file:
        path: "{{ item }}"
        owner: oracle
        group: dba
        recurse: no
      with_fileglob:
        - "{{ destination_dir }}/*.sql"
