---
- name: Copy and move all SQL files from /tmp to /home/ubcustom/deployments/kamote, then chown oracle:dba (as root)
  hosts: all
  become: yes
  remote_user: root
  vars:
    destination_dir: "/home/ubcustom/deployments/kamote"
  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ destination_dir }}"
        state: directory
        owner: oracle
        group: dba
        mode: '0755'

    - name: Copy all SQL files from /tmp to the destination directory
      copy:
        src: "{{ item }}"
        dest: "{{ destination_dir }}/"
        owner: oracle
        group: dba
        mode: '0644'
        remote_src: yes
      with_fileglob:
        - "/tmp/*.sql"

    - name: Remove SQL files from /tmp after copying
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/tmp/*.sql"

    - name: Ensure correct ownership and permissions on all SQL files in destination
      file:
        path: "{{ item }}"
        owner: oracle
        group: dba
        mode: '0644'
        recurse: no
      with_fileglob:
        - "{{ destination_dir }}/*.sql"
