---
- name: Copy *.sql files and chown deployments directory
  hosts: all
  become: yes
  vars:
    variable: kamote# Override with --extra-vars "variable=your_value"
    src_dir: /tmp   # Set to directory containing your .sql files
    dest_dir: "/home/ubcustom/deployments/{{ variable }}"
    deployments_dir: "/home/ubcustom/deployments"
  tasks:
    - name: Ensure target directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        owner: oracle
        group: dba
        mode: '0755'

    - name: Copy all .sql files with permissions preserved
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}/"
        owner: oracle
        group: dba
        mode: preserve
      with_fileglob:
        - "{{ src_dir }}/*.sql"

    - name: Recursively chown deployments directory
      ansible.builtin.file:
        path: "{{ deployments_dir }}"
        owner: oracle
        group: dba
        recurse: yes
