---
- name: Copy files from 192.168.100.32:/tmp/dep/ to all hosts
  hosts: all
  gather_facts: false
  vars:
    src_host: 192.168.100.32
    src_path: /tmp/dep/
    dest_path: /home/ubcustom/deployments/kamote/
  tasks:
    - name: Synchronize files from remote src_host to managed node
      ansible.builtin.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        mode: pull
        archive: yes
        compress: yes
        times: yes
      delegate_to: "{{ src_host }}"
      become: yes
      become_user: ubcustom
