---
- name: Example playbook that logs in as root
  hosts: all
  become: yes
  remote_user: root
  tasks:
    - name: Print current user
      command: whoami
      register: whoami_out

    - name: Show current user
      debug:
        msg: "Logged in as: {{ whoami_out.stdout }}"
