---
- name: Connect to Oracle database as oracle user and show database name
  hosts: target_hosts
  become: yes
  become_user: oracle
  tasks:
    - name: Run SQL*Plus and show connected database
      shell: |
        sqlplus -S /nolog <<EOF
        conn TCTDBS/TCTDBS@primedb
        SELECT name FROM v\$database;
        exit
        EOF
      register: sqlplus_output

    - name: Show SQL*Plus output
      debug:
        var: sqlplus_output.stdout
